#-----------------BUILDER-----------------
#-----------------------------------------
FROM node:24.21.0-alpine3.23 AS builder

RUN npm install --global npm@11.19.0

ENV SHARP_FORCE_GLOBAL_LIBVIPS=1 \
    PKG_CONFIG_PATH=/usr/local/lib/pkgconfig \
    LD_LIBRARY_PATH=/usr/local/lib
# inspired by https://github.com/lovell/sharp/issues/4273 and https://github.com/lovell/sharp/issues/4267
RUN apk add --no-cache --update \
    vips \
    vips-dev \
    vips-heif \
    vips-magick \
    curl \
    meson \
    ninja \
    imagemagick-dev \
    libheif-dev \
    libheif \
    libpng \
    libjpeg-turbo \
    libde265 \
    libwebp \
    libraw-dev \
    g++ \
    make \
    gcc \
    build-base \
    python3 \
    pkgconfig

COPY docker/build-libvips.sh /tmp/build-libvips.sh
RUN sh /tmp/build-libvips.sh && rm /tmp/build-libvips.sh

COPY pigallery2-release /app
WORKDIR /app
RUN npm install --no-package-lock --save-dev node-addon-api@8.5.0 node-gyp@11.5.0  && \
    npm run build --prefix node_modules/sharp && \
    npm prune --omit=dev && \
    npm cache clean --force


RUN mkdir -p /app/data/config && \
    mkdir -p /app/data/db && \
    mkdir -p /app/data/images && \
    mkdir -p /app/data/tmp


#-----------------MAIN--------------------
#-----------------------------------------
FROM node:24.21.0-alpine3.23 AS main
WORKDIR /app
ENV NODE_ENV=production \
    LD_LIBRARY_PATH=/usr/local/lib \
    # overrides only the default value of the settings (the actual value can be overwritten through config.json)
    default-Database-dbFolder=/app/data/db \
    default-Media-folder=/app/data/images \
    default-Media-tempFolder=/app/data/tmp \
    default-Extensions-folder=/app/data/config/extensions \
    # flagging dockerized environment
    PI_DOCKER=true

EXPOSE 80
ARG TARGETARCH
RUN apk add --no-cache \
    vips vips-cpp vips-heif vips-magick libraw ffmpeg \
    && if [ "$TARGETARCH" = "amd64" ]; then \
        echo "Building for amd64, adding intel-media-driver" && \
        apk add --no-cache intel-media-driver; \
    fi \
    && rm -rf /var/cache/apk/*
COPY --from=builder /app /app
COPY --from=builder /usr/local/lib /usr/local/lib

# Run build time diagnostics to make sure the app would work after build is finished
RUN ["node", "--expose-gc", "./src/backend/index", "--run-diagnostics", "--config-path=/app/diagnostics-config.json", "--Server-Log-level=silly"]
HEALTHCHECK --interval=40s --timeout=30s --retries=3 --start-period=60s \
  CMD wget --quiet --tries=1 --no-check-certificate --spider \
  http://127.0.0.1:80/heartbeat || exit 1

# after a extensive job (like video converting), pigallery calls gc, to clean up everything as fast as possible
# Exec form entrypoint is need otherwise (using shell form) ENV variables are not properly passed down to the app
ENTRYPOINT ["node", "--expose-gc", "./src/backend/index", "--config-path=/app/data/config/config.json"]
